export const Types = {
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN: "LOGIN",
  UPDATE_PROFILE_PICTURE: "UPDATE_PROFILE_PICTURE",
  FORM_SUBMISSION_STATUS: "FORM_SUBMISSION_STATUS",
};
